name: SECRETS TEST

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
