name: SECRETS TEST

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: COPY KEY
        env:
          PRIVATE_KEY: ${{secrets.TEST_PRIVATE_KEY}}
          PRIVATE_KEY_ID: ${{secrets.TEST_PRIVATE_KEY_ID}}
        run: |
          PRIVATE_KEY_FILE_NAME="AuthKey_${PRIVATE_KEY_ID}.p8" 
          mkdir ~/.private_keys
          echo ${PRIVATE_KEY} >> ~/.private_keys/$PRIVATE_KEY_FILE_NAME
          ls ~/.private_keys
          
